name: SyncFlareMC
version: '${project.version}'
authors:
  - Ixf1nity
  - tomasalias
  - iagof-dev
main: com.iagof.syncflare.NgrokCommunication
api-version: 1.20
load: STARTUP
libraries:
  - net.dv8tion:JDA:5.0.0-beta.18